{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: {{ .Values.keycloak.namespace }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.admin.password | b64enc }}
---
{{- end }}
{{- if .Values.cloudManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-manager-credentials
  namespace: {{ .Values.cloudManager.namespace }}
type: Opaque
data:
  client-secret: {{ .Values.cloudManager.config.introspectClientSecret | b64enc }}
{{- end }}
