{{- if .Values.operatorService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operatorService.serviceAccount.name }}
  namespace: {{ .Values.operatorService.namespace }}
  labels:
    app: operator-service
---
{{- end }}
{{- if .Values.fileService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fileService.serviceAccount.name }}
  namespace: {{ .Values.fileService.namespace }}
  labels:
    app: file-service
{{- end }}
